name: Bug Report
description: File a bug report.
labels: ["bug"]

body:
  - type: dropdown
    id: version-type
    attributes:
      label: Version type
      description: What version type of Ampersand are you running?
      options:
        - Stable
        - CI build
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Specify the version here
    validations:
      required: true

  - type: dropdown
    id: distribution-channel
    attributes:
      label: Where and how did you get Ampersand from?
      multiple: false
      options:
        - Android (Google Play Store)
        - Android (downloaded elsewhere)
        - iOS (SideStore)
        - iOS (other means of sideloading)
        - Windows (downloaded through our website)
        - macOS (downloaded through our website)
        - Linux (downloaded through our website)
        - Linux / Fedora (downloaded through our GitHub)
        - Linux / Ubuntu or Debian (downloaded through our GitHub)
        - Linux / Arch (built through our PKGBUILD)
        - Linux / Other (built yourself)
    validations:
      required: true

  - type: dropdown
    id: starting-database
    attributes:
      label: Did you import your data?
      multiple: false
      options:
        - No
        - Yes, from a previous Ampersand installation
        - Yes, from Octocon
        - Yes, from Simply Plural
        - Yes, from PluralKit
        - Yes, from TupperBox
    validations:
      required: true

  - type: textarea
    id: device
    attributes:
      label: Device
      description: |
        On which device are you using Ampersand?

        If you're on a desktop/laptop, specify:
          - OS name and version
          - CPU model, amount of RAM available (available means what's reported as available from your system information section)
          - GPU model (optional, do include in case of graphical glitches)
          - Bonus steps for Windows:
            - Exact version of Edge WebView2, find that in your computer's app list.
          - Bonus steps for Linux:
            - Exact version of webkit2gtk-4.1 for your distribution.
        
        Else, if you're on a mobile device, specify:
          - if an iPhone, the exact model and iOS version;
          - if an Android, the exact model and Android version, plus the following:
            - If using a custom ROM, please tell us which flavor it is (eg. LineageOS, GrapheneOS);
            - Do tell us your WebView name and version (Settings -> Apps -> Show all apps -> Android WebView / Android System WebView / {Your vendor's name here, eg. Huawei} WebView);
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: |
        Tell us all of the following:
        - A brief description of the bug you're facing;
        - The steps needed to reproduce this bug;
        - If this bug is consistent (eg. you reboot the app and it's still there all the times);
        - If this bug can be worked around, tell us how you did work around it as it might give us some clues as to what's broken;
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: Relevant log output
      description: If you're tech inclined and you know how to get a log, put it here.
      render: shell
