name: Build Ampersand

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [main]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment
permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: ${{ github.ref_name == 'main' && 'build-dev' || 'build-release' }}
  cancel-in-progress: true

jobs:
  prepare-build:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'yarn'
    - name: Install frontend dependencies
      run: yarn install --frozen-lockfile
    - name: Get Ampersand version from upgrade-vcs script
      run: yarn run upgrade-vcs
      env:
        NO_PATCH: 1
    - name: Remove old prerelease draft and create new dev tag
      if: ${{ github.ref_name == 'main' }}
      run: |
        git tag dev
        git push origin dev
        gh release delete dev -y || true
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Publish release
      id: release
      uses: softprops/action-gh-release@v3.0.0
      with:
        name: ${{ github.ref_name != 'main' && format('Release ({0})', env.AMPERSAND_VERSION) || format('CI build ({0})', env.AMPERSAND_VERSION) }}
        tag_name: ${{ github.ref_name != 'main' && github.ref_name || 'dev' }}
        prerelease: ${{ github.ref_name == 'main' && true || false }}
        draft: true
        generate_release_notes: true
  build-android:
    uses: ./.github/workflows/build-android.yml
    needs: prepare-build
    secrets: inherit
    with:
      upload_url: ${{ needs.prepare-build.outputs.upload_url }}
    permissions:
      contents: write
  build-ios:
    uses: ./.github/workflows/build-ios.yml
    needs: prepare-build
    secrets: inherit
    with:
      upload_url: ${{ needs.prepare-build.outputs.upload_url }}
    permissions:
      contents: write
  build-pc:
    uses: ./.github/workflows/build-pc.yml
    needs: prepare-build
    secrets: inherit
    with:
      upload_url: ${{ needs.prepare-build.outputs.upload_url }}
    permissions:
      contents: write
  release:
    needs: [prepare-build, build-android, build-ios, build-pc]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Publish release
        uses: softprops/action-gh-release@v3.0.0
        with:
          tag_name: ${{ github.ref_name != 'main' && github.ref_name || 'dev' }}
          prerelease: ${{ github.ref_name == 'main' && true || false }}
          draft: false
