# Simple workflow for building Ampersand as an Android application
name: Build for Android

on:
  workflow_call:
    inputs:
      upload_url:
        type: string
        required: true
      ampersand_version:
        type: string
        required: true
      ampersand_build_type:
        type: string
        required: true
    secrets:
      ANDROID_KEY_ALIAS:
        required: true
      ANDROID_KEY_PASSWORD:
        required: true
      ANDROID_KEY_BASE64:
        required: true
      ANDROID_STORE_PASSWORD:
        required: true

env:
  AMPERSAND_VERSION: ${{ inputs.ampersand_version }}
  AMPERSAND_BUILD_TYPE: ${{ inputs.ampersand_build_type }}
  AMPERSAND_BUILD_TARGET: android

# Sets the GITHUB_TOKEN permissions to allow deployment
permissions:
  contents: write

concurrency:
  group: ${{ github.ref_name == 'main' && 'build-android-dev' || 'build-android-release' }}
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy-android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev libwebkit2gtk-4.1-dev librsvg2-dev patchelf xdg-utils
      - name: Set up package manager
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21.0.12+8.0.LTS'
      - name: Set up Android SDK
        uses: android-actions/setup-android@v4
        with:
          log-accepted-android-sdk-licenses: false
          cmdline-tools-version: 14742923
          packages: "build-tools;35.0.0 ndk;29.0.14206865 platform-tools platforms;android-36.1 sources;android-36.1"
      - name: Get Rust toolchain version
        id: rust_toml_parse
        run: pnpm run get-rust-version
      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ steps.rust_toml_parse.outputs.rust_toolchain_version }}
          components: ${{ steps.rust_toml_parse.outputs.rust_toolchain_components }}
          target: ${{ steps.rust_toml_parse.outputs.rust_toolchain_targets }}
          rust-src-dir: "src-tauri"
      - name: Update versioning
        run: pnpm run upgrade-vcs
      - name: Set up Android signing
        run: |
          cd src-tauri/gen/android
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > local.properties
          echo "password=${{ secrets.ANDROID_KEY_PASSWORD }}" >> local.properties
          base64 -d <<< "${{ secrets.ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> local.properties
      - name: Build app (APK)
        run: |
          pnpm tauri android build --apk --target aarch64 armv7 --split-per-abi --ci
        env:
          NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/29.0.14206865/
          RUST_BACKTRACE: full
      - name: Publish artifact (APK - ARMv7)
        uses: actions/upload-artifact@v7
        with:
          name: Android App (APK - ARMv7)
          archive: false
          path: |
            ./src-tauri/gen/android/app/build/outputs/apk/arm/release/ampersand*-arm-release.apk
      - name: Publish artifact (APK - ARM64)
        uses: actions/upload-artifact@v7
        with:
          name: Android App (APK - ARM64)
          archive: false
          path: |
            ./src-tauri/gen/android/app/build/outputs/apk/arm64/release/ampersand*-arm64-release.apk
      - name: Publish to release (APK)
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: ./src-tauri/gen/android/app/build/outputs/apk/*/release/ampersand-*-release.apk
