# Simple workflow for building Ampersand as an iOS application
name: Build for iOS

on:
  workflow_call:
    inputs:
      upload_url:
        type: string
        required: true

# Sets the GITHUB_TOKEN permissions to allow deployment
permissions:
  contents: write

concurrency:
  group: ${{ github.ref_name == 'main' && 'build-ios-dev' || 'build-ios-release' }}
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'
      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.15.2
        with:
          rust-src-dir: "src-tauri"
          target: "aarch64-apple-ios"
      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile
      - name: Update versioning
        run: yarn run upgrade-vcs
      - name: Build unsigned IPA
        run: bash ./make_unsigned_ipa.sh
        env:
          IPA_PATH: Ampersand-${{ env.AMPERSAND_VERSION }}.ipa
      - name: Generate AltStore JSON
        if: startsWith(github.ref, 'refs/tags/')
        run: node make_altstore_json.mjs
        env:
          IPA_PATH: Ampersand-${{ env.AMPERSAND_VERSION }}.ipa
          GITHUB_REF_NAME: ${{ github.ref_name }}
      - name: Publish artifact (IPA and AltStore JSON)
        uses: actions/upload-artifact@v4
        with:
          name: iOS App (IPA and AltStore JSON)
          path: |
            Ampersand-${{ env.AMPERSAND_VERSION }}.ipa
            altstore.json
          if-no-files-found: warn
      - name: Publish to release (iOS IPA)
        if: startsWith(github.ref, 'refs/tags/')
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: Ampersand-${{ env.AMPERSAND_VERSION }}.ipa
      - name: Publish to release (AltStore JSON)
        if: startsWith(github.ref, 'refs/tags/')
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: altstore.json