name: Build Ampersand

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [main]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment
permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: 'build'
  cancel-in-progress: true

jobs:
  prepare-build:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Remove old prerelease draft and create new dev tag
      run: |
        git tag dev
        git push origin dev
        gh release delete dev -y || true
      env:
        GH_TOKEN: ${{ github.token }}
  build-android:
    uses: ./.github/workflows/build-android.yml
    needs: prepare-build
    secrets: inherit
    permissions:
      contents: write
  build-pc:
    uses: ./.github/workflows/build-pc.yml
    needs: prepare-build
    secrets: inherit
    permissions:
      contents: write
  release:
    needs: [prepare-build, build-android, build-pc]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile
      - name: Get Ampersand version from upgrade-vcs script
        run: yarn run upgrade-vcs
        env:
          NO_PATCH: 1
      - name: Publish release
        uses: softprops/action-gh-release@v2.4.1
        with:
          name: ${{ github.ref_name != 'main' && format('Release ({0})', env.AMPERSAND_VERSION) || format('CI build ({0})', env.AMPERSAND_VERSION) }}
          tag_name: ${{ github.ref_name != 'main' && github.ref_name || 'dev' }}
          prerelease: false
          draft: false
          generate_release_notes: true
          append_body: false