# Simple workflow for building Ampersand as a PC application
name: Build for PC

on:
  workflow_call:
    inputs:
      upload_url:
        type: string
        required: true

# Sets the GITHUB_TOKEN permissions to allow deployment
permissions:
  contents: write

concurrency:
  group: ${{ github.ref_name == 'main' && 'build-pc-dev' || 'build-pc-release' }}
  cancel-in-progress: true

jobs:
  deploy-pc:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-26'
            args: '--target universal-apple-darwin'
          - platform: 'ubuntu-latest'
            args: ''
          - platform: 'windows-latest'
            args: ''
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'
      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.16.0
        with:
          rust-src-dir: "src-tauri"
          target: ${{ matrix.platform == 'macos-26' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile
      - name: Update versioning
        run: yarn run upgrade-vcs
      - name: Build Ampersand
        run: yarn tauri build --ci ${{ matrix.args }}
      - name: Publish artifacts (Linux)
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v7
        with:
          name: PC build for Linux
          path: |
            ./src-tauri/target/release/bundle/deb/Ampersand_*.deb
            ./src-tauri/target/release/bundle/rpm/Ampersand-*.rpm
            ./src-tauri/target/release/bundle/appimage/Ampersand_*.AppImage
      - name: Publish artifacts (macOS)
        if: matrix.platform == 'macos-26'
        uses: actions/upload-artifact@v7
        with:
          name: PC build for macOS
          path: |
            ./src-tauri/target/universal-apple-darwin/release/bundle/dmg/Ampersand_*.dmg
      - name: Publish artifacts (Windows)
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v7
        with:
          name: PC build for Windows
          path: |
            ./src-tauri/target/release/bundle/msi/Ampersand*.msi
      - name: Publish to release (Linux DEB)
        if: matrix.platform == 'ubuntu-latest'
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: ./src-tauri/target/release/bundle/deb/Ampersand_*.deb
      - name: Publish to release (Linux RPM)
        if: matrix.platform == 'ubuntu-latest'
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: ./src-tauri/target/release/bundle/rpm/Ampersand-*.rpm
      - name: Publish to release (Linux AppImage)
        if: matrix.platform == 'ubuntu-latest'
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: ./src-tauri/target/release/bundle/appimage/Ampersand_*.AppImage
      - name: Publish to release (macOS DMG)
        if: matrix.platform == 'macos-26'
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: ./src-tauri/target/universal-apple-darwin/release/bundle/dmg/Ampersand_*.dmg
      - name: Publish to release (Windows MSI)
        if: matrix.platform == 'windows-latest'
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: src-tauri\target\release\bundle\msi\Ampersand*.msi