name: Build Ampersand

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [main]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment
permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: ${{ github.ref_name == 'main' && 'build-dev' || 'build-release' }}
  cancel-in-progress: true

jobs:
  prepare-build:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url || steps.release_rc.outputs.upload_url || steps.release_unstable.outputs.upload_url }}
      ampersand_version: ${{ steps.vcs.outputs.ampersand_version }}
      ampersand_build_type: ${{ steps.vcs.outputs.ampersand_build_type }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'yarn'
    - name: Install frontend dependencies
      run: yarn install --frozen-lockfile
    - name: Get Ampersand version from upgrade-vcs script
      id: vcs
      run: yarn run upgrade-vcs
      env:
        NO_PATCH: 1
    - name: Ensure tag is clean
      run: |
        git tag --delete ${{ env.TAG }} || true
        git tag ${{ env.TAG }}
        git push origin --delete ${{ env.TAG }} || true
        git push origin ${{ env.TAG }}
        gh release delete ${{ env.TAG }} -y || true
      env:
        GH_TOKEN: ${{ github.token }}
        TAG: ${{ github.ref_name != 'main' && github.ref_name || 'dev' }}
    - name: Prepare release (Unstable)
      id: release_unstable
      if: ${{ steps.vcs.outputs.ampersand_build_type == 'unstable' }}
      uses: softprops/action-gh-release@v3.0.0
      with:
        name: ${{ format('Unstable build ({0})', steps.vcs.outputs.ampersand_version)}}
        tag_name: dev
        prerelease: true
        draft: true
    - name: Prepare release (Release candidate)
      id: release_rc
      if: ${{ steps.vcs.outputs.ampersand_build_type == 'rc-sideload' }}
      uses: softprops/action-gh-release@v3.0.0
      with:
        name: ${{ format('Release candidate ({0})', steps.vcs.outputs.ampersand_version)}}
        prerelease: true
        draft: true
    - name: Prepare release (Release)
      id: release
      if: ${{ steps.vcs.outputs.ampersand_build_type == 'stable-sideload' }}
      uses: softprops/action-gh-release@v3.0.0
      with:
        name: ${{ format('Release ({0})', steps.vcs.outputs.ampersand_version)}}
        prerelease: false
        draft: true
  build-android:
    uses: ./.github/workflows/build-android.yml
    needs: prepare-build
    secrets: inherit
    with:
      upload_url: ${{ needs.prepare-build.outputs.upload_url }}
      ampersand_version: ${{ needs.prepare-build.outputs.ampersand_version }}
      ampersand_build_type: ${{ needs.prepare-build.outputs.ampersand_build_type }}
    permissions:
      contents: write
  build-ios:
    uses: ./.github/workflows/build-ios.yml
    needs: prepare-build
    secrets: inherit
    with:
      upload_url: ${{ needs.prepare-build.outputs.upload_url }}
      ampersand_version: ${{ needs.prepare-build.outputs.ampersand_version }}
      ampersand_build_type: ${{ needs.prepare-build.outputs.ampersand_build_type }}
    permissions:
      contents: write
  build-pc:
    uses: ./.github/workflows/build-pc.yml
    needs: prepare-build
    secrets: inherit
    with:
      upload_url: ${{ needs.prepare-build.outputs.upload_url }}
      ampersand_version: ${{ needs.prepare-build.outputs.ampersand_version }}
      ampersand_build_type: ${{ needs.prepare-build.outputs.ampersand_build_type }}
    permissions:
      contents: write
  release:
    needs: [prepare-build, build-android, build-ios, build-pc]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Publish release
        uses: softprops/action-gh-release@v3.0.0
        with:
          tag_name: ${{ github.ref_name != 'main' && github.ref_name || 'dev' }}
          draft: false
